version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnpmjs.org
    volumes:
      - cnpm-files-volume:/var/data/cnpm_data
    ports:
      - "7001:7001"
      - "7002:7002"
    environment :
      - OSS_ENDPOINT=****
      - OSS_BUCKET=****
      - OSS_AK=****
      - OSS_AK_SECRET=**** 
      - RDS_DB_HOST=**** 
      - RDS_DB_NAME=**** 
      - RDS_DB_USER_NAME=**** 
      - RDS_DB_USER_PASSWORD=**** 

volumes:
  cnpm-files-volume:

